# Generated by Django 4.1.3 on 2022-11-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('category', models.CharField(choices=[('TOP', 'Top Stories'), ('LATEST', 'Latest'), ('POPULAR', 'Popular'), ('DISCOVER', 'Discover'), ('HERO', 'Hero')], default='TOP', max_length=20, verbose_name='Category')),
                ('slug', models.SlugField(max_length=150, unique_for_date='pub_date')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='post/')),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_tag', to='tags.tag')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.topic')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-title', 'pub_date'],
                'get_latest_by': '-pub_date',
            },
        ),
    ]
