# Generated by Django 4.1.3 on 2022-11-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TOP', 'Top Stories'), ('LATEST', 'Latest'), ('POPULAR', 'Popular'), ('DISCOVER', 'Discover'), ('MEDICAL', 'Medical'), ('HERO', 'Hero')], default='TOP', max_length=20, verbose_name='Category'),
        ),
    ]
