# Generated by Django 4.1.3 on 2022-11-30 10:38

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
