# Generated by Django 4.1.3 on 2022-11-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('BLUE', 'blue'), ('PRIMARY', 'primary'), ('RED', 'red'), ('ORANGE', 'orange'), ('YELLOW', 'yellow'), ('PURPLE', 'purple'), ('PINK', 'pink')], default='PRIMARY', max_length=50, verbose_name='BACKGROUND COLOR')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
