# Generated by Django 4.1.3 on 2022-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='tags/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('BLUE', 'blue'), ('PRIMARY', 'primary'), ('RED', 'red'), ('ORANGE', 'orange'), ('YELLOW', 'yellow'), ('PURPLE', 'purple'), ('PINK', 'pink'), ('GREEN', 'green')], default='PRIMARY', max_length=50, verbose_name='BACKGROUND COLOR'),
        ),
    ]
